---
- name: Configurar aula ICO1
  hosts: ico1
  become: true

  roles:
    - common
    - java21
    - libreoffice_base
    - geany
    - vlc
    - gthumb
    - packettracer

- name: Configurar controlador local
  hosts: localhost
  connection: local
  become: true

  roles:
    - common
    - java21
    - libreoffice_base
    - geany
    - vlc
    - gthumb
    - packettracer
