---
- name: Configurar aula ICO1
  hosts: ico1
  become: true

  roles:
    - common
    - libreoffice_base
    - geany
    - vlc
    - gthumb
    - packettracer

    # VirtualBox 7.2.8 + Extension Pack ya viene en la imagen base
    
