---
- name: Configurar aula ICO4
  hosts: ico4
  become: true

  roles:
    - common
    - vokoscreen
    - veyon
    - java21
    - scenebuilder
    - mysql
    - oracle_client
    - python
    - packettracer

- name: Configurar controlador local
  hosts: localhost
  connection: local
  become: true

  roles:
    - common
    - vokoscreen
    - veyon
    - java21
    - scenebuilder
    - mysql
    - oracle_client
    - python
    - packettracer
    
