---
- name: Configurar aula ICO4
  hosts: ico4
  become: true

  roles:
    - common
    - vokoscreen
    - veyon
    - java21
    - vscode
    - scenebuilder
    - mysql
    - oracle_client
    - python

    # VirtualBox 7.2.8 + Extension Pack ya viene en la imagen base
    # p7zip esta incluido en common

    # Packet Tracer 9.0 pendiente para septiembre
    # - packet_tracer
