---
- name: Configurar aula ICO5
  hosts: ico5
  become: true

  roles:
    - common
    - vscode
    - python
    - mysql
    - anaconda
    - coppeliasim

    # VirtualBox ya viene en la imagen base

    # Packet Tracer 9.0 pendiente para septiembre
    # - packet_tracer
