---
- name: Configurar aula ICO5
  hosts: ico5
  become: true

  roles:
    - common
    - vscode
    - python
    - mysql
    - anaconda
    - coppeliasim
    - packettracer

    # VirtualBox ya viene en la imagen base
    
