---
- name: Configurar aula ICO5
  hosts: ico5
  become: true

  roles:
    - common
    - python
    - mysql
    - anaconda
    - coppeliasim
    - packettracer
    
- name: Configurar controlador local
  hosts: localhost
  connection: local
  become: true

  roles:
    - common
    - python
    - mysql
    - anaconda
    - coppeliasim
    - packettracer
    
