---
- name: Configurar aula ICO6
  hosts: ico6
  become: true

  roles:
    - common
    - vokoscreen
    - veyon
    - java21
    - vscode
    - scenebuilder
    - mysql

    # VirtualBox 7.2.8 + Extension Pack ya viene en la imagen base
    # p7zip esta incluido en common

    # Packet Tracer 9.0 pendiente para septiembre
    # - packet_tracer
