---
- name: Configurar aula ICO6
  hosts: ico6
  become: true

  roles:
    - common
    - vokoscreen
    - veyon
    - java21
    - scenebuilder
    - mysql
    - packettracer

- name: Configurar controlador local
  hosts: localhost
  connection: local
  become: true

  roles:
    - common
    - vokoscreen
    - veyon
    - java21
    - scenebuilder
    - mysql
    - packettracer 
