---
- name: Configurar aula ICO7
  hosts: ico7
  become: true

  roles:
    - common
    - vokoscreen
    - veyon
    - firefox
    - chromium
    - gimp
    - inkscape
    - pencil
    - vlc
    - audacity
    - mysql
    - postgresql
    - java25
    - git
    - maven

