---
- name: Configurar aula ICO7
  hosts: ico7
  become: true

  roles:
    - common
    - vokoscreen
    - veyon
    - vscode
    - firefox
    - chromium
    - gimp
    - inkscape
    - pencil
    - vlc
    - audacity
    - mysql
    - postgresql
    - java25
    - docker
    - git
    - maven

    # VirtualBox 7.2.8 + Extension Pack ya viene en la imagen base
    # p7zip esta incluido en common
